"""Data classes for database records."""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field


@dataclass
class Alert:
    """An alert generated by the detection pipeline."""

    severity: str  # "info", "warning", "critical"
    category: str  # "rogue_ap", "deauth_attack", "anomaly", "new_device"
    title: str
    detail: str
    evidence: dict = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)
    source_mac: str | None = None
    bssid: str | None = None
    channel: int | None = None

    def to_dict(self) -> dict:
        return asdict(self)

    def evidence_json(self) -> str:
        return json.dumps(self.evidence, default=str)


@dataclass
class APRecord:
    """Known AP inventory record."""

    bssid: str
    ssid: str
    security: str  # "open", "wpa2", "wpa3", etc.
    first_seen: float
    last_seen: float
    legitimacy_score: float  # 0.0-1.0 from AP classifier
    channel: int | None = None
    rssi_avg: float | None = None
    ie_fingerprint: str = ""  # hash of IE tag order


@dataclass
class DeviceRecord:
    """Known device inventory record."""

    mac: str
    device_class: str  # "iphone", "android", "laptop", "iot", etc.
    confidence: float  # 0.0-1.0
    first_seen: float
    last_seen: float
    is_randomized: bool = False  # locally administered MAC
    probe_fingerprint: str = ""


@dataclass
class ChannelSnapshot:
    """Periodic channel utilization snapshot."""

    timestamp: float
    channel: int
    packet_count: int
    unique_bssids: int
    deauth_rate: float
    avg_rssi: float | None = None
